---
- hosts: local
  gather_facts: true
  name: Pre tasks before execute the ansible modules
  vars_files:
    - vars/python3.yaml
  roles:
    - name: Install python3
      role: ericsysmin.python3
    - name: Install pip-python
      role: geerlingguy.pip

- hosts: local
  name: Install tools or softwares which support our job
  vars_files:
    - vars/asdf.yaml
    - vars/brew.yaml
  roles:
    - name: Install git
      role: geerlingguy.git
    - name: Install docker
      role: ericsysmin.docker.docker
    - name: Install ruby
      role: geerlingguy.ruby
    # - name: Install homebrew
    #   role: homebrew
    - name: Install asdf plugins
      role: markosamuli.asdf
    # - name: Install brew plugins
    #   role: grog.package
