---
- hosts: local
  gather_facts: true
  name: Pre tasks before execute the ansible modules
  vars_files:
    - vars/python3.yaml
  roles:
    - name: Install python3
      role: ericsysmin.python3
    - name: Install pip-python
      role: geerlingguy.pip

- hosts: local
  name: Install external package
  vars_files:
    - vars/dotfiles.yaml
    - vars/ohmyzsh.yaml
  roles:
      - name: external-package
      - name: gantsign.oh-my-zsh
      - name: geerlingguy.dotfiles

- hosts: local
  name: Install tools or softwares which support our job
  vars_files:
    - vars/asdf.yaml
    - vars/brew.yaml
  roles:
    - name: Install git
      role: geerlingguy.git
    - name: Install docker
      role: ericsysmin.docker.docker
    - name: Install ruby
      role: geerlingguy.ruby
    - name: Install asdf plugins
      role: markosamuli.asdf
    - name: Install vim-plug
      role: vim-plug
