---
- hosts: all
  name: Pre tasks before execute the ansible modules
  vars_files:
    - vars/python3.yaml
    - vars/pip.yaml
  roles:
    - name: Install python3
      role: ericsysmin.python3
      become: yes
    - name: Install pip-python
      role: geerlingguy.pip
      become: yes

- hosts: all
  name: Install external package
  vars_files:
    - vars/dotfiles.yaml
    - vars/ohmyzsh.yaml
  roles:
      - name: Install oh-myz-sh
        role: gantsign.oh-my-zsh
      - name: Install external packages
        role: external-package
      - name: Install dotfiles
        role: geerlingguy.dotfiles
 
