---
- hosts: all
  name: Pre tasks before execute the ansible modules
  vars_files:
    - vars/python3.yaml
    - vars/pip.yaml
  roles:
    - name: Install python3
      role: ericsysmin.python3
      become: yes
    - name: Install pip-python
      role: geerlingguy.pip
      become: yes

- hosts: all
  name: Install external package
  vars_files:
    - vars/dotfiles.yaml
    - vars/ohmyzsh.yaml
  roles:
      - name: gantsign.oh-my-zsh
      - name: geerlingguy.dotfiles

- hosts: all
  name: Install tools or softwares which support our job
  vars_files:
    - vars/asdf.yaml
    - vars/brew.yaml
  roles:
    - name: Install asdf plugins
      role: markosamuli.asdf
