---
roles:
  - name: ericsysmin.python3
  - name: geerlingguy.pip
  - name: markosamuli.asdf
  - name: geerlingguy.git
  - name: geerlingguy.ruby
collections:
  - name: ericsysmin.docker
  - name: community.general
