---
- name: Create directory fonts
  file:
    path: ~/.fonts
    state: directory
    mode: "0755"

- name: Download fonts
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf
    dest: ~/.fonts/Droid \Sans \Mono \for \Powerline \Nerd \Font \Complete.otf

- name: Update fonts
  command: fc-cache -fv

