---
- name: Create directory ohmytmux
  become: yes
  file:
    state: directory
    path: /opt/ohmytmux
    mode: "0755"

- name: Clone ohmytmux repository
  become: yes
  git:
    repo: "https://github.com/gpakosz/.tmux.git"
    dest: /opt/ohmytmux

- name: Soft link ohmytmux
  become: yes
  file:
    state: link
    src: /opt/ohmytmux/.tmux
    path: "~/.tmux"

- name: Copy tmux conf local into homedir
  become: yes
  copy:
    src: "~/.tmux/.tmux.conf.local"
    dest: "~"
