---
- name: Clone ohmytmux repository
  git:
    repo: "https://github.com/gpakosz/.tmux.git"
    dest: "~/"

- name: Soft link ohmytmux
  file:
    state: link
    src: "~/.tmux/.tmux.conf"
    path: "~/"

- name: Copy tmux conf local into homedir
  copy:
    src: "~/.tmux/.tmux.conf.local"
    dest: "~/"
