---
- name: Make sure Homebrew directories exists
  file:
    path: /usr/local/*
    state: directory
    mode: 0775
    owner: root
    group: root
    recurse: yes
  become: yes

- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: /tmp/install

- name: Install Homebrew
  shell: /bin/bash -c "/tmp/install" < /dev/null

- name: Set permissions for /usr/local/*
  file:
    path: "{{ item }}"
    mode: "0775"
    owner: "{{ username }}"
    group: wheel
    recurse: yes
    state: directory
  become: yes
  with_items: "{{ homebrew_paths }}"
  ignore_errors: yes

- name: Fix ACL permissions for multiple users
  become: yes
  command: 'chmod -R +a "group:admin allow list,add_file,search,delete,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" {{ item }}'
  args:
    warn: no
  with_items: "{{ homebrew_paths }}"
  ignore_errors: yes

- name: Reset the Homebrew Library repo
  git: repo=https://github.com/Homebrew/brew.git
    dest=/usr/local/Homebrew/Library
    clone=no
    update=yes
    force=yes

- name: Update Homebrew (first try may fail)
  homebrew: update_homebrew=yes
  become: no
  ignore_errors: yes

- name: Update Homebrew
  homebrew: update_homebrew=yes
  become: no
